# Generated by Django 5.2.5 on 2026-04-23 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Information_System', '0007_coursemapping_group_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='ARCHI2025', max_length=50)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_code_changes', to='Information_System.admin')),
            ],
            options={
                'verbose_name_plural': 'System Auth Code',
                'db_table': 'system_auth_code',
            },
        ),
    ]

